### PR TITLE
fix max length tag

### LINKED ISSUE #603: [Bug]: Possible to input more than max char limit for post by inserting an emoji
### Describe the bug

By inputting an emoji at the end of a post, it is possible to exceed the 1000 char limit and click post. Nexus doesn't serve it up in the feed though.

### Reproduce

_No response_

### Screenshots / Recording

https://github.com/user-attachments/assets/69f4e54c-8b31-46fb-8f10-3e10eb367fee

### Web Browser

Version 130.0.6723.117 (Official Build) (arm64)

### Pubky App Version

_No response_

### Console log output

_No response_

### PR DESCRIPTION
**Pull request by flaviomoceri**
@catch-21  saw that if you added 19 characters and then added an emoji you were able to exceed the maxlength limit of the tag (20)

This PR you should fix

### CODE REVIEW

**Comment by catch-21** [comment]
It would be nice to see this handled by a common library to improve readability. This would also avoid having the hard coded maxlength replicated over multiple components, which could lead to error if not all are changed at a later stage.

**Comment by catch-21** [comment]
Please see my comment here https://github.com/pubky/pubky-app/issues/603#issuecomment-2482792219

**Comment by flaviomoceri** [comment]
@catch-21 try now

**Comment by catch-21** [comment]
Verified in 5d3fee74b41577ca5b8578ae5a479522a8cdc425
LGTM :+1:

**Review by MiguelMedeiros — APPROVED** [review]

**Pull request merged**
