### PR TITLE
fix qrLogin

### LINKED ISSUE #759: [Feature]: Improve Pubky Ring QR sign in UX
### Describe the problem

Currently, the QR shown at https://staging.pubky.app/sign-in will time out with an ugly `Crypto(SecretBox(Error))` message.
Screenshot 2024-12-17 at 12 15 53

### Describe the solution

The Http Relay request should be re-set when it has timed out or is nearing timeout so the user can scan this QR even if the sign in page has been sat idle for longer than a couple of minutes

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by flaviomoceri**
Hey Miguel, in another commit I think you commented this line of code, please leave it, it is used to fix https://github.com/pubky/pubky-app/issues/759

I improved it because if for some reason there is a timeout etc, by calling the function I recreate a new qrCode, if instead there is an access problem it means that the qrCode is still valid so I do not regenerate it and show the error message

### CODE REVIEW

**Comment by flaviomoceri** [comment]
@MiguelMedeiros Maybe it is better to regenerate the qrCode only when the error is timeout?
I think that in any case other than login failure, regenerating the qrCode is only positive

**Comment by MiguelMedeiros** [comment]
I've removed this code, because it was causing an infinite loop. Degrading performance a lot.
To address this, we could refine the error-handling logic to ensure it only triggers when appropriate. 

Here’s an updated suggestion that ensures no unnecessary reloads or recursive calls:

```ts
try {
  const errorMessage = error === 'dead::Error' ? 'Failed to login.' : null;

  if (errorMessage) {
    setLoginError(errorMessage);
  } else {
    handleGenerateAuthUrl();
  }
} catch (error) {
  console.error('Unexpected error occurred:', error);
}
```

**Comment by flaviomoceri** [comment]
Oh, I didn't notice, sorry, check now, is it ok?

**Comment by MiguelMedeiros** [comment]
Changed the update of the QRcode only if there is an error of login. otherwise it will not reload the qr.

**Review by MiguelMedeiros — APPROVED** [review]

**Comment by catch-21** [comment]
see https://github.com/pubky/pubky-app/issues/759#issuecomment-2566571885

**Pull request merged**
