### PR TITLE
Feat: adding buttons

### LINKED ISSUE #61: Feat: add `Button` component
Image

### PR DESCRIPTION
**Pull request by flaviomoceri**
Added `PrimaryButtton` and `SecondaryButton` component

There is currently an error in PrimaryButton, the border does not follow the borderRadius of the button, I tried to fix it but without success, I'll try again tomorrow

Screenshot 2024-01-09 212833
Screenshot 2024-01-09 212850

### CODE REVIEW

**Comment by flaviomoceri** [comment]
As in the other components I can't apply the borderRadius, furthermore the hover doesn't seem to work
I'll spend some time fixing the errors later, meanwhile I'll proceed with creating the other buttons

Screenshot 2024-02-08 162121
Screenshot 2024-02-08 162139

**Comment by flaviomoceri** [comment]
Same problem in this commit, hover doesn't work, can't apply the borderRadius to the border and neither can the borderStyle dashed
Screenshot 2024-02-09 091215
Screenshot 2024-02-09 091430

**Comment by flaviomoceri** [comment]
Same problem, hover doesn't work
Screenshot 2024-02-09 105501

**Comment by flaviomoceri** [comment]
@MiguelMedeiros 
General issues:
1. Hover doesn't work
2. Apply borderRadius to the buttons

**Comment by MiguelMedeiros** [comment]
Hey @flaviomoceri a few comments on this PR:

- This PR is too big, we should make 1 PR per Button type
  - 1 PR for Button.Create
  - 1 PR for Button.Large
  - 1 PR for Button.Medium
  - etc...
- We should use tailwind classes instead of css in js
- I will talk to @aldertnl so we can remove all the gradients for now so we can push the code faster. Conic background gradiend with overflow-hidden and rounded border it's not compatible with all browsers. I suggest that we keep the design flat for the MVP in Viareggio (remove all the gradients for now)

I will close this PR. Lets make a pair programming on monday so you can follow my pattern.

**Pull request closed without merging**
