### PR TITLE
feat: adding input

### LINKED ISSUE #62: (Pubky Design Content) - Form
Image

### PR DESCRIPTION
**Pull request by flaviomoceri**
Screenshot 2024-02-09 120220

### CODE REVIEW

**Comment by flaviomoceri** [comment]
Screenshot 2024-02-09 135651

**Comment by flaviomoceri** [comment]
I was unable to add the borderColor

Screenshot 2024-02-09 145109

**Comment by flaviomoceri** [comment]
I can't add the colored border to the checkInbox
Screenshot 2024-02-09 154332

**Comment by flaviomoceri** [comment]
Screenshot 2024-02-09 161946

**Comment by flaviomoceri** [comment]
Screenshot 2024-02-09 165015

**Comment by MiguelMedeiros** [comment]
Hey @flaviomoceri i will close this PR, bc it need a major refactor, same issues that i mention in the #67 .

**Pull request closed without merging**
